packages_base:
  - build-essential
  - curl
  - git
  - htop
  - jq
  - mosquitto-clients
  - wget
  - screen
  - tmux
  - vim

kubernetes_packages:
  - name: kubelet
    state: absent
  - name: kubectl
    state: absent
  - name: kubeadm
    state: absent
  - name: kubernetes-cni
    state: absent
