packages_base:
  - build-essential
  - cifs-utils
  - curl
  - git
  - gnupg
  - htop
  - jq
  - keychain
  - mosquitto-clients
  - nfs-common
  - python-is-python3
  - python3-dev
  - python3-pip
  - python3-venv
  - rsync
  - software-properties-common
  - sshpass
  - screen
  - tmux
  - unzip
  - vim
  - wget

kubernetes_packages:
  - name: kubelet
    state: absent
  - name: kubectl
    state: present
  - name: kubeadm
    state: absent
  - name: kubernetes-cni
    state: absent

hashicorp_products:
  - name: terraform
