
services:
  gitlab:
    image: gitlab/gitlab-ee:17.8.6-ee.0
    container_name: gitlab
    restart: always
    hostname: "git.${HOMELAB_DOMAIN_MAIN}"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://git.${HOMELAB_DOMAIN_MAIN}'
    ports:
      - '19080:80'
      - '19443:443'
      - '19022:22'
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
    shm_size: '256m'

volumes:
  gitlab-config:
  gitlab-logs:
  gitlab-data: