services:
  n8n:
    container_name: n8n
    image: louislam/uptime-kuma:1
    restart: always
    environment:
      - TZ="Europe/London"
      - GENERIC_TIMEZONE="Europe/London"
    volumes:
      - n8n-data:/home/node/.n8n
    ports:
      - 5678:5678
    
volumes:
  n8n-data:
