services:
  openwebui:
    container_name: openwebui
    image: ghcr.io/open-webui/open-webui:main
    restart: always
    volumes:
      - openwebui-data:/app/backend/data
    ports:
      - 3000:3000
    
volumes:
  openwebui-data:
