- name: Install required Galaxy roles
  ansible.builtin.command: "ansible-galaxy install -r {{ pull_home }}/ansible/requirements.yml -p {{ pull_home }}/ansible/roles"
  args:
    chdir: "{{ pull_home }}/ansible/roles"

- name: Install environment files
  ansible.builtin.template:
    src: templates/ansible-pull.env.j2
    dest: /etc/default/ansible-pull

- name: Install service
  ansible.builtin.template:
    src: templates/ansible-pull.service.j2
    dest: /etc/systemd/system/ansible-pull.service

- name: Install timer
  ansible.builtin.template:
    src: templates/ansible-pull.timer.j2
    dest: /etc/systemd/system/ansible-pull.timer

- name: Reload systemd daemon configuration
  command: systemctl daemon-reload

- name: Enable and start timer
  ansible.builtin.systemd:
    name: ansible-pull.timer
    state: restarted
    enabled: true

