services:
  woodpecker-server:
    image: woodpeckerci/woodpecker-server:v3
    restart: always
    ports:
      - 8011:8000
      - 9000:9000
    volumes:
      - woodpecker-server-data:/var/lib/woodpecker/
    environment:
      - WOODPECKER_OPEN=true
      - WOODPECKER_HOST=https://ci.${HOMELAB_DOMAIN_MAIN}
      - WOODPECKER_GITHUB=true
      - WOODPECKER_GITHUB_CLIENT=${WOODPECKER_GITHUB_CLIENT}
      - WOODPECKER_GITHUB_SECRET=${WOODPECKER_GITHUB_SECRET}
      - WOODPECKER_AGENT_SECRET=${WOODPECKER_AGENT_SECRET}
      - WOODPECKER_ENVIRONMENT=TEST:123,SMTP_DSN:smtp://${FASTMAIL_SMTP_USER}:${FASTMAIL_SMTP_PASSWORD}@${FASTMAIL_SMTP_HOST}:587?verify_peer=1,SMTP_FROM:${WOODPECKER_EMAIL_ADDRESS},EMAIL_NOTIFICATIONS:${EMAIL_NOTIFICATIONS}
      
  woodpecker-agent:
    image: woodpeckerci/woodpecker-agent:v3
    restart: always
    command: agent
    depends_on:
      - woodpecker-server
    ports:
      - 3002:3000
    volumes:
      - woodpecker-agent-config:/etc/woodpecker
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WOODPECKER_SERVER=${WOODPECKER_SERVER}
      - WOODPECKER_AGENT_SECRET=${WOODPECKER_AGENT_SECRET}

volumes:
  woodpecker-server-data:
  woodpecker-agent-config: