- name: Apt Update & Upgrade
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: true

- name: Dist Upgrade
  ansible.builtin.apt:
    upgrade: dist
    update_cache: true

- name: Install Packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop: "{{ packages_base }}"
