- name: Download setup script
  ansible.builtin.get_url:
    url: https://dl.cloudsmith.io/public/infisical/infisical-cli/setup.deb.sh
    dest: /tmp/infisical-setup.sh

- name: Run setup script
  ansible.builtin.command: bash /tmp/infisical-setup.sh

- name: Install packages
  ansible.builtin.apt:
    name: infisical
    state: present
    update_cache: true

- name: Remove setup script
  ansible.builtin.file:
    path: /tmp/infisical-setup.sh
    state: absent
