---
- name: Install and configure NGINX web server
  hosts: all
  become: true

  tasks:
    - name: Ensure NGINX is installed
      apt:
        name: nginx
        state: present
      when: ansible_os_family == "Debian"
