---
- name: Setup Playbook
  hosts: all
  become: true

  tasks:
    - name: Ansible Pull Bootstrap
      include_role:
        name: ansible_pull
    - name: Package Maintenance
      include_role:
        name: packages
    - name: Setup Docker
      include_role:
        name: geerlingguy.docker
      when: enable_docker | bool