---
- name: Setup Playbook
  hosts: all
  become: true

  tasks:
    - name: Ansible Pull Bootstrap
      include_role:
        name: ansible_pull
    - name: Setup Docker
      include_role:
        name: geerlingguy.docker