---
- name: Setup Playbook
  hosts: all
  become: true

  tasks:

    # Setup Ansible Pull (install roles etc.)
    - name: Ansible Pull Bootstrap
      include_role:
        name: ansible_pull

    # Update, Upgrade & Install OS Packages
    - name: Package Maintenance
      include_role:
        name: packages
  
    # Setup Docker
    - name: Setup Docker
      include_role:
        name: geerlingguy.docker
      when: enable_docker | bool
      
    # Setup Helm
    - name: Setup Helm
      include_role:
        name: geerlingguy.helm
      vars:
        helm_version: "v3.16.3"
      when: enable_helm | bool
      
    # Setup Hashicorp Tools
    - name: Setup Hashicorp Tools
      include_role:
        name: buluma.hashicorp
      when: enable_hashicorp | bool
      
    # Setup Kubernetes
    # - name: Setup Kubernetes
    #   include_role:
    #     name: geerlingguy.kubernetes
    #   when: enable_kubernetes | bool