---
- name: Update Playbook
  hosts: all
  become: true

  tasks:

    # Setup Ansible Pull (install roles etc.)
    - name: Ansible Pull Bootstrap
      include_role:
        name: ansible_pull
  
    # Update, Upgrade & Install OS Packages
    - name: Package Maintenance
      include_role:
        name: packages
