services:
  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:latest
    restart: always
    command: tunnel --no-autoupdate run --protocol quic --token ${CLOUDFLARE_TUNNEL_TOKEN}
    volumes:
      - /etc/localtime:/etc/localtime:ro
    