steps:
  mail:
    image: deblan/woodpecker-email
    settings:
      dsn: ${SMTP_DSN}
      from:
        address: louis@ptre.es
        name: "CI"
      evaluate: 'commit.branch == "main"'
      recipients:
        - jinglemansweep@gmail.com
      level: success
      recipients_only: false
      content:
        subject: "[{{ pipeline.status }}] {{ repo.full_name }} ({{ commit.branch }} - {{ commit.sha[0:8] }}"
        body: |
          {{ commit.sha }}<br>
          {{ pipeline.status }}<br>
          {{ commit.author_email }}<br>
      attachments:
        - log/*