services:
  beszel:
    container_name: beszel
    image: henrygd/beszel:latest
    restart: always
    volumes:
      - beszel-data:/beszel_data
    ports:
      - 8090:8090
    
volumes:
  beszel-data:
