name: Ansible

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  Ansible:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Infisical Login
      uses: Infisical/secrets-action@v1.0.9
      with:
        project-slug: "${{ secrets.INFISICAL_PROJECT_SLUG }}"
        env-slug: "${{ vars.INFISICAL_ENV_SLUG }}"
        method: "universal"
        client-id: "${{ secrets.INFISICAL_CLIENT_ID }}"
        client-secret: "${{ secrets.INFISICAL_CLIENT_SECRET }}"
    - name: "Install Ansible"
      uses: alex-oleshkevich/setup-ansible@v1.0.1
      with:
        version: "${{ vars.ANSIBLE_VERSION }}"
    - name: Tailscale
      uses: tailscale/github-action@v3
      with:
        oauth-client-id: "${TAILSCALE_OAUTH_CLIENT_ID}"
        oauth-secret: "${TAILSCALE_OAUTH_CLIENT_SECRET}"
        tags: tag:ci
    - name: Ping
      run: |
        ping -c 10 10.1.1.116
    - name: Run Playbook
      uses: dawidd6/action-ansible-playbook@v3
      with:
        playbook: update.yml
        directory: ./ansible
        configuration: |
          [defaults]
          remote_user = ansible
          host_key_checking = false
          result_format = yaml
          nocows = false
        key: ${ANSIBLE_SSH_PRIVATE_KEY}
        inventory: |
          [all]
          services.adm.ptre.es  ansible_host=10.1.1.116
        vault_password: ${ANSIBLE_VAULT_PASSWORD}
        requirements: requirements.yml
        options: |
          -vvvvv
        