name: Infisical Secrets

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  Secrets:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Infisical Login
      uses: Infisical/secrets-action@v1.0.9
      with:
        project-slug: "${{ secrets.INFISICAL_PROJECT_SLUG }}"
        env-slug: "${{ vars.INFISICAL_ENV_SLUG }}"
        method: "universal"
        client-id: "${{ secrets.INFISICAL_CLIENT_ID }}"
        client-secret: "${{ secrets.INFISICAL_CLIENT_SECRET }}"
    - name: Debug Output
      run: |
        [ ! "${GITHUB_ACTION_DUMMY}" == "DUMMY" ] && echo "Secret Test Failed" && exit 1
        echo "Secret Test Passed"